version: '3.8'

services:
  app:
    build: .
    container_name: ai_calendar_agent_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5001
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
      - ./app.py:/app/app.py
      - ./src:/app/src
